### ISSUE TITLE
Key repeat?

### ISSUE THREAD

**Issue by kpmgeek** [ksherlock/itty-bitty-vtty#1]
No matter what I have set in the IIgs control panel for input repeat (I'm on a rom01 so I cannot access any program-speciic settings that are in the control panel on rom 03), I cannot get key repeat to work.  This works correctly under Spectrum.

**Comment by kpmgeek** [comment]
If this is a DECARM issue, the default *should be* repeat.

**Comment by ksherlock** [comment]
It looks like my DECARM check is backwards (on is off, off is on). I'll build a new version.  In the meantime you can turn it off (to turn it on) by going into local mode (command-L) then typing ESC [ ? 8 l (then command-L to exit local mode).

The ROM 3 control panel is display only so you're not missing much.

**Comment by ksherlock** [comment]
There's a new disk image available.

**Comment by kpmgeek** [comment]
Cheers
